title: Daniel Hallqvist
description: Just another blog about web and system development

url: http://brianmaierjr.github.com/long-haul
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 10

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about


social:
   github: dhq
   twitter: dhallqvist
   facebook: danielhq
   email: dhallqvist91@gmail.com
   linkedin: daniel-hallqvist-51257455

google_analytics: "UA-19437538-1"
